LDFLAGS = -lm -lGL -lglfw -lstdc++ -lpthread
CXXFLAGS += -D__UNIX_JACK__
LDFLAGS += -ljack -lsoundpipe -lsndfile -ldl
CFLAGS += -DEXPORT=""
CXXFLAGS += -DEXPORT=""
CFLAGS += -DFULLSCREEN -g
CFLAGS += -DDRAW_POINTER

debug: eyejam
	gdb -ex=r eyejam
